### ISSUE TITLE
app$$1.instance storage is not a function

### ISSUE THREAD

**Issue by RakWojciech** [hamedbaatour/angularfire-lite#17]
Hi after npm run build:ssr and npm run serve:ssr I see this in my console:

`TypeError: app$$1.instance(...).storage is not a function
    at new AngularFireLiteStorage (F:\xampp\htdocs\blogger\dist\server.js:148901:42)
    at _createClass (F:\xampp\htdocs\blogger\dist\server.js:13282:20)
    at _createProviderInstance$1 (F:\xampp\htdocs\blogger\dist\server.js:13254:26)
    at resolveNgModuleDep (F:\xampp\htdocs\blogger\dist\server.js:13239:17)
    at NgModuleRef_.get (F:\xampp\htdocs\blogger\dist\server.js:14476:16)
    at resolveDep (F:\xampp\htdocs\blogger\dist\server.js:14966:45)
    at createClass (F:\xampp\htdocs\blogger\dist\server.js:14836:32)
    at createDirectiveInstance (F:\xampp\htdocs\blogger\dist\server.js:14673:37)
    at createViewNodes (F:\xampp\htdocs\blogger\dist\server.js:16131:53)
    at createRootView (F:\xampp\htdocs\blogger\dist\server.js:16020:5)`

re-install angularfire-lite - nothing changed
re-install all node_modules - nothing changed
comment out/delete everything about storage ( import, in constructor, in code )

I use angular 5 with universal

**Comment by RakWojciech** [comment]
@hamedbaatour I can share my repo for this if you want

**Comment by hamedbaatour** [comment]
@RakWojciech can you share a simple reproduction of the issue also can you upgrade to 5.2 and give a try
